read -p "Donnez moi un chiifre: " CHIFFRE_UTILISATEUR
for i in $CHIFFRE_UTILISATEUR
    do
    echo "`expr $CHIFFRE_UTILISATEUR \* $CHIFFRE_UTILISATEUR`"
    CHIFFRE_PUISSANCE_2="`expr $CHIFFRE_UTILISATEUR \* $CHIFFRE_UTILISATEUR`"
done